name: Weekly Weather Update

on:
  schedule:
    - cron: '0 6 * * 0'  # Runs every Sunday at 6:00 UTC
  workflow_dispatch:      # Allows manual trigger in GitHub UI

jobs:
  update-weather:
    runs-on: ubuntu-latest

    env:
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      GOOGLE_SHEET_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weather updater
        run: python weather_api_sheet_updater.py